### ISSUE TITLE
Challenging

### ISSUE THREAD

**Issue by tiny-1996** [InvokerMaster/Selenium-XPath-Beginner#1]
Hey,  
I can understand how deep your knowledge of selenium is through this repo.
Is this your main repo? :dancer:

**Comment by InvokerMaster** [comment]
I think I made this when I am 4 years old >:<

**Comment by tiny-1996** [comment]
:wolf: oops! I didn't teach you like that at that time.
oh..., I'm embarrassed....  :pig:

**Comment by InvokerMaster** [comment]
Oops. Sorry for making you dissappointed 😠

**Comment by tiny-1996** [comment]
haha... have manner.. :muscle:
